# Use the official Python image as the base image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the working directory
COPY . .

# Expose the port that the Flask app will run on
EXPOSE 8080

# Start the Flask app
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"]